### ISSUE TITLE
Full network path in outputs from detection models

### ISSUE THREAD

**Issue by staciekoslovsky-noaa** [readicculus/pep_gui#31]
Include full network path, rather than just image name, in outputs from processing jobs

**Comment by readicculus** [comment]
Found a flag in the pipeline `video_input` process that allows the full path to be sent through the pipeline.  This means that full paths will now be in the output image list .txt files in addition to full paths to images being in the detections csv frame column.
See https://github.com/readicculus/pep_gui/commit/7107a5305b5fbc825da6d672fffde039db08c601
